### ISSUE TITLE
Consider rebranding to AS4

### ISSUE THREAD

**Issue by johndpope** [craiggrummitt/ActionSwift3#5]
Firstly - I somehow think Adobe will never ever release as4. 
anyone searching could find this repo - and get onboard. 
http://www.yeahbutisitflash.com/?p=4812

https://plus.google.com/+JosephLabrecque/posts/HEr4m1eLZgC

If adobe open a lawsuit because of supposed trademarks on AS4 - it could only be a good PR exercise for this repo.

**Comment by craiggrummitt** [comment]
Another v interesting suggestion! 
My first instinct was that a new version of the language(i.e. AS4) would be an evolution on the syntax of the language rather than a migration to a different platform, but when I thought about it, it _is_ an evolution of the syntax of the language, as it's using Swift at its base rather than ECMAScript.
So as a practical idea, I quite like it. As a PR idea - interesting suggestion(although maybe this post might in itself do that!) - on the other hand it'd be a shame to drop 'Swift' from the title. How would you see it? Rename the repo, or perhaps just mention AS4 in the description?
I think you should be ActionSwift3 evangelist, @johndpope, you've got great ideas, keep 'em coming!

**Comment by johndpope** [comment]
latest idea - spring cleaning old github issues. 
:)

**Comment by craiggrummitt** [comment]
:) I was happy leaving them there to brew on, but thanks for spring cleaning for me @johndpope !
